# For more information: https://laravel.com/docs/sail
version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        image: php:8.0-apache
        volumes:
#            - ./php/src:/var/www/html/
            - '.:/var/www/html'
        ports:
            - 8000:80

